version: "3.7"

services:
  database_nodetype:
    image: postgres
    container_name: database_nodetype
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nodetype
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app: 
    build: .
    container_name: nodetype
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host


volumes:
  pgdata: